# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-27 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilalMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_date', models.DateField(auto_now_add=True)),
                ('milal_friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.MilalFriend')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
