# Generated by Django 3.2.8 on 2025-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='bonus_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bonus percentage to apply to volunteer hours (e.g., 10 for 10% bonus)', null=True),
        ),
    ]
