# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-27 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230227_0409'),
        ('users', '0002_update_to_volunteer_model'),
    ]

    operations = [
    ]
