# Generated by Django 3.2.8 on 2025-07-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer_bonus_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name set for email account', max_length=50),
        ),
    ]
