# Generated by Django 4.2 on 2023-09-15 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerHours",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("saturday_agape", "Saturday Agape"),
                            ("other", "Other"),
                        ],
                        help_text="Service type that hours were collected for",
                        max_length=30,
                    ),
                ),
                ("service_date", models.DateTimeField(help_text="Datetime of service")),
                (
                    "hours",
                    models.FloatField(
                        help_text="Number of hours served for service type"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Text field for holding misc data", null=True
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        help_text="Email account used to register the hours. Useful if volunteer account not created yet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.emailaccount",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.volunteer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MilalMatching",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_date",
                    models.DateField(auto_now_add=True, help_text="Date of matching"),
                ),
                (
                    "milal_friend",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.milalfriend",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.volunteer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
